### ISSUE TITLE
Add Microsoft's logo to the Working Group webpage

### ISSUE THREAD

**Issue by ZahraFazli** [microprofile/microprofile-site#115]
Please add Microsoft's logo to the Working Group webpage: https://microprofile.io/workinggroup/

![MP-Partner-logos_Microsoft](https://user-images.githubusercontent.com/50374570/175035810-8c751711-3974-4a68-9172-0e7fd51d4122.png)

Thank you.

**Comment by ZahraFazli** [comment]
Hi @cesarhernandezgt I am referring to the working group webpage (https://microprofile.io/workinggroup/). The page does not seem to have Microsoft's logo.

**Comment by cesarhernandezgt** [comment]
Hi @ZahraFazli , 

I double-checked and this repository is not the correct one for adding the logo to the website.

For the correct process and repository, please refer to the `Members Onboarding` guide you can find at https://microprofile.io/workinggroup/

![image](https://user-images.githubusercontent.com/1454523/176283657-d63f0b70-9e88-43d4-99c8-e3f3047531c5.png)

**Comment by rstjames** [comment]
to do for me : add logo and check slider timing

**Comment by rstjames** [comment]
added and tested
