### ISSUE TITLE
Change [See the Code] link to point at new location/page

### ISSUE THREAD

**Issue by kwsutter** [microprofile/microprofile-site#22]
Currently, the [See the Code] link points at the github microprofile project.  We have moved all of the "real code" to Eclipse, with only the microprofile.io specific code and configuration in the old repos.  John committed some code to change this link to the Developers link on our Eclipse MP site, but I don't think this is sufficient.

We have two repo projects now -- the official Eclipse-based repositories, and the microprofile.io repositories for the site maintenance.  The [See the Code] link should probably point at a new page with both sets of links.  Most developers will want access to the "real code", while the site maintenance people will want access to the original repositories.

**Comment by karianna** [comment]
I think HEAD has this changed link but it's just not been released yet?

**Comment by jclingan** [comment]
Fixed. Site needs to be pushed to production, however.
