### ISSUE TITLE
Create voting card for MicroProfile.IO

### ISSUE THREAD

**Issue by RockClimberT** [microprofile/microprofile-site#43]
**MicroProfile Logo Revamp - Voting**
- Voting goes from July 10-21, 2017
- Website card **live date Sunday, July 9th at 6PM EST**
- Website card **removal date Friday, July 21st at 6PM EST**

Requirements:
- Homepage card (see image)
- Image on left side (to be provided by Ryan)
- Text on right side:
_MicroProfile Logo Redesign
Vote For Your Favorite Logo
Voting open July 10 - 21, 2017_
_**VOTE NOW**_ <CTA button: URL - will send to Thiago on Sunday at 5:30PM EST>

![mp_voting_card](https://user-images.githubusercontent.com/6722471/27890716-6a644c8c-61a9-11e7-9390-46871f007449.png)

**Comment by rstjames** [comment]
Attached is the left card visual. 
![logo-vote-image](https://user-images.githubusercontent.com/12132146/27900304-21bffef6-622e-11e7-95a2-5fc8dad93f04.png)

**Comment by tveronezi** [comment]
PR ready. Missing URL.

https://github.com/microprofile/microprofile-site/pull/44

Will update the PR on Sunday as soon as I have the new URL.
