### ISSUE TITLE
Create new branch for website improvements 

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-site#99]
Hello, 
As part of the work that is required by https://github.com/microprofile/microprofile-wg/issues/65, we need a new branch in https://github.com/microprofile/microprofile-site/ to push the first prototypes and iterate over it.

cc: @Emily-Jiang @secondsun @Dexmaster

**Comment by Emily-Jiang** [comment]
Hi @cesarhernandezgt sure, no problem. Let's create a branch. What should be branch be called?

**Comment by cesarhernandezgt** [comment]
Hi @Emily-Jiang , `website-improve` please.

**Comment by Emily-Jiang** [comment]
@cesarhernandezgt done

**Comment by cesarhernandezgt** [comment]
THank you @Emily-Jiang !
